name: publish

on:
  push:
    branches:
      - main
    paths:
      - subdir/**
      - .github/workflows/publish.yml
    permissions:
      id-token: write
      contents: read

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the hello-docker Docker image
        run: |
          docker build --tag ghcr.io/floriankehrle/hello-docker-gcr-demo:latest -f subdir/Dockerfile
          docker run ghcr.io/floriankehrle/hello-docker-gcr-demo:latest
          docker push ghcr.io/floriankehrle/hello-docker-gcr-demo:latest
