#
name: publish

on:
  push:
    branches:
      - main
    paths:
      - subdir/**
      - .github/workflows/publish.yml
    permissions:
      id-token: write
      contents: read

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the gitactions_test Docker image
        run: |
          docker build --tag ghcr.io/floriankehrle/gitactions_test:latest -f VeldtAR.Server/Dockerfile .
          docker push ghcr.io/floriankehrle/gitactions_test:latest
